// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Camera: typeof import('./components/Camera.vue')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignaturePad: typeof import('./components/SignaturePad.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    XTabContents: typeof import('./components/x-components/XTabContents.vue')['default']
    XTabs: typeof import('./components/x-components/XTabs.vue')['default']
  }
}
