// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Camera: typeof import('./components/Camera.vue')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    copy: typeof import('./components/Logo.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HeroiconsArrowRightOnRectangle: typeof import('~icons/heroicons/arrow-right-on-rectangle')['default']
    HeroiconsLockClosedSolid: typeof import('~icons/heroicons/lock-closed-solid')['default']
    HeroiconsMinus: typeof import('~icons/heroicons/minus')['default']
    HeroiconsStar: typeof import('~icons/heroicons/star')['default']
    HeroiconsUserSolid: typeof import('~icons/heroicons/user-solid')['default']
    IconHeroiconsMinus: typeof import('~icons/ic/on-heroicons-minus')['default']
    IconHeroiconsUserSolid: typeof import('~icons/ic/on-heroicons-user-solid')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/x-components/XSideMenu.vue')['default']
    SignaturePad: typeof import('./components/SignaturePad.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    XSection: typeof import('./components/x-components/XSection.vue')['default']
    XSideMenu: typeof import('./components/x-components/XSideMenu.vue')['default']
    XSwitch: typeof import('./components/x-components/XSwitch.vue')['default']
    XSwitch2: typeof import('./components/x-components/XSwitch-2.vue')['default']
    XTabContents: typeof import('./components/x-components/XTabContents.vue')['default']
    XTabs: typeof import('./components/x-components/XTabs.vue')['default']
  }
}
